### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by FarhanAnsari92** [checkout/frames-ios#135]
[!] The [Target] target has transitive dependencies that include statically linked binaries: (/Pods/CheckoutEventLoggerKit/CheckoutEventLoggerKit.xcframework)

pod 'Frames', '3.5.2'
xcode 13.2.1
iOS minimum target v11.0

**Comment by deepesh-vasthimal-cko** [comment]
Hi @FarhanAnsari92 Can you please give us more details to reproduce the issue. Some steps would be nice.

**Comment by FarhanAnsari92** [comment]
I installed the sdk using SPM.
