### ISSUE TITLE
"CardView" nib but the view outlet was not set

### ISSUE THREAD

**Issue by sravani552** [checkout/frames-ios#17]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[UIViewController _loadViewFromNibNamed:bundle:] loaded the "CardView" nib but the view outlet was not set.'

App is getting crash.

**Comment by deepesh-vasthimal-cko** [comment]
Hi Sravani

Please can you check if you have connected the CardView outlet from nib or storyboard to the cardview UI component itself if not please can you connect them.

**Comment by deepesh-vasthimal-cko** [comment]
@sravani552 since there has been no response. I am closing this issue for now. Please feel free to reopen it.
