### ISSUE TITLE
Swift 5 conversion error.

### ISSUE THREAD

**Issue by wasim-dev** [checkout/frames-ios#2]
I am using latest Xcode version 10.2.1 (10E1001) with my project in Swift 5. While i compile project framework gives compile time error and i can see Swift 5 conversion is available. But when i convert it it gives error.  

**To Reproduce**
1. Create a project with Xcode 10.2.1 (10E1001).
2. Add Frames by pods.
3. Compile project and it will as you for Swift 5 conversion with an error.
4. Perform conversion, You can see actual problem now.

**Desktop :**
 - Xcode: 10.2.1 (10E1001)
 - Swift Version 5.

**Comment by nicolas-maalouf-cko** [comment]
Hi @wasim-dev 

I just ran the project on Xcode 10.2.1 along with the conversion of the syntax to Swift 5 and all worked smoothly.

Can you please provide more details about the error you're getting?

Thank you

**Comment by wasim-dev** [comment]
Hi @nicolas-maalouf-cko 
Thanks, For looking in to the problem. I tried to replicate the issue. Just figured out that this only generates if we have old version of Frames SDK and then it updated. Now i deleted old SDK by removing pods and then add new one which is working perfect.

Thanks
Have great evening.
