### ISSUE TITLE
Xcode 12

### ISSUE THREAD

**Issue by fahedalahmad** [checkout/frames-ios#22]
Xcode 12: 'PhoneNumberKit' has different definitions in different modules; first difference is definition in module 'PhoneNumberKit.Swift' found method with no designater initializer

i am using PhoneNumberKit 
[https://github.com/marmelroy/PhoneNumberKit]

**Comment by christiygag** [comment]
Same issue here. I have integrated PhoneNumberKit and frames-ios through pods. But the definitions are conflicting in Xcode 12.

Any workarounds?

**Comment by fahedalahmad** [comment]
@christiygag  I have manually named PhoneNumberKit into PhoneNumberKitFrames in Frames framework and it worked for me. until one of them decide to change the class name.

**Comment by daven-gomes-cko** [comment]
Hi @fahedalahmad, @christiygag,

Frames-ios contains PhoneNumberKit in its repository (as copied source files, not integrated with any dependency managers). If you were to remove PhoneNumberKit from your Pods (or your other integration method), would your apps compile? My theory is your apps would then refer to the PhoneNumberKit classes/methods in Frames-ios.

This could be a temporary solution for now while we investigate this issue.

**Comment by erenbesel** [comment]
Any update on this @daven-gomes-cko ?
Removing PhoneNumberkit pod is no help as it has its own updates for Xcode 12. I am looking into downloading Frames-ios manually until you guys provide a fix. How can we setup frames manually? Installation steps only show Cocoapods and Carthage.

**Comment by daven-gomes-cko** [comment]
Hi @erenbesel, we are planning to release a new version of Frames that will rename our use of `PhoneNumberKit` next week. For now, can you point your dependency manager to the branch `make-phone-number-kit-internal-rename` please? This renames our uses of `PhoneNumberKit` so you can continue to use `PhoneNumberKit` directly with your own integration. Thanks.

**Comment by erenbesel** [comment]
Hi @daven-gomes-cko, thank you. If you are releasing an update next week, may I ask will you also update your own phonenumberkit or only rename it? Maybe we can only use yours if it will be up to date. Thanks.

**Comment by daven-gomes-cko** [comment]
Hi @erenbesel, sure we can update our version of PhoneNumberKit _and_ rename it. When we release it I'll post in this thread to let you know it's available.

**Comment by daven-gomes-cko** [comment]
Hi all, a new version of Frames is available (3.1.0). This updates `PhoneNumberKit` and renames it to `CKOPhoneNumberKit`. Please let us know if you have any other issues. 🙂
