### ISSUE TITLE
Is 3D Secure available?

### ISSUE THREAD

**Issue by Sayanta-Redapple** [checkout/frames-ios#23]
Hello,

It will be great if the framework handle #D Secure payment.

**Comment by kevin-jarvis-cko** [comment]
Hi @Sayanta-Redapple, thanks for your feedback. To handle 3D Secure, you need to take the redirect URL that [your server receives when requesting the payment](https://api-reference.checkout.com/#tag/Payments/paths/~1payments/post) and pass it to your app. You can then display the 3D Secure view to your user, and listen for success/failure URL redirections.

Frames-ios can handle the webview and success/failure URL redirection if you'd like to use this method - see https://checkout.github.io/frames-ios/ios-example.html for detail of that approach.

Does that cover what you were hoping to achieve?

**Comment by deepesh-vasthimal-cko** [comment]
@Sayanta-Redapple closing this issue now. However if you still have any questions please feel free to re-open the issue.
