### ISSUE TITLE
Apps submitted with 3.1.0 are rejected from the AppStore

### ISSUE THREAD

**Issue by sebskuse** [checkout/frames-ios#26]
**Describe the bug**
It appears that in 3.1.0 there is a new shell script included as part of the copy phase - `update.sh` (https://github.com/checkout/frames-ios/blob/master/Source/PhoneNumberKit/Resources/update.sh). It looks like this was pulled in when upgrading `PhoneNumberKit`. When validating our app, we are receiving the following error:

`
Invalid Signature. Code object is not signed at all. The file at path [OurApp.app/Frameworks/FramesIos.framework/update.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html (1091)
`

Doing some digging on StackOverflow, it seems that `.sh` files must be signed (or removed, if they're unnecessary): https://stackoverflow.com/questions/29788601/error-itms-90035-xcode.

Reverting back to 3.0.5 removes this error.

**To Reproduce**
1. Build an app with `FramesIos.framework` included
2. Submit for review, or validate (I'm using `altool` here)

**Expected behavior**
The app should pass AppStore validation.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14

**Comment by daven-gomes-cko** [comment]
Hi @sebskuse thanks for reporting this. We've merged a temporary fix by removing the `update.sh` file from the repo. If this is urgent, you can point your dependency manager to the `master` branch for now. Once we do some more testing and release a new version of Frames, I will update this issue to let you know.

**Comment by sebskuse** [comment]
@daven-gomes-cko great, thanks for resolving this so quickly!

**Comment by daven-gomes-cko** [comment]
Hi @sebskuse, no worries! Frames 3.1.1 has now been released.
