### ISSUE TITLE
html error response

### ISSUE THREAD

**Issue by ViktorAmelin** [checkout/frames-ios#3]
**Describe the bug**
Xcode 10.3
Using your test cards for dev environment
4242 4242 4242 4242 cvv: 100

**Here is what I'm sending:**
REST POST https://sandbox.checkout.com/api2/v2/payments {'content-type': 'application/json', 'Authorization': 'sk_test_2e41ac0e-fa36-47e6-bbb8-f9c903d2d5c5'} {'source': {'type': 'token', 'token': 'card_tok_735752A2-41C8-41F3-836A-5D59BA562B77'}, 'amount': '1300', 'currency': 'USD', 'payment_type': 'Regular', 'reference': 'A12807|30619', 'capture': True, 'metadata': {'udf2': '9b92d120695a77345aabb8d5b92b9266'}, 'failure_url': 'https://tr3.admiralmarkets.com/transactions/deposit/error/checkout?order_id=A12807|30619', 'success_url': 'https://tr3.admiralmarkets.com/transactions/deposit/success/checkout?order_id=A12807|30619', 'customer': {'email': '33@admiralmarkets.com'}, '3ds': {'enabled': True}} [PENDING].

**And getting huge amount of html code instead (**

**Expected behavior**
At least I would like to get an error message

**Smartphone (please complete the following information):**
 - Device: any
 - OS: 12.4

**Comment by nicolas-maalouf-cko** [comment]
Hi @ViktorAmelin 

It seems you are mixing 2 endpoints here:
1) https://sandbox.checkout.com/api2/v2/tokens which is the only URL that can be called directly from mobile SDKS with the API public key
2) https://api.sandbox.checkout.com/payments which is to be used from a backend server with the API secret key along with the temporary card token obtained in 1) 

Please make sure to never use any endpoints involving the secret key from a mobile app. This would be breaching PCI compliance

The flow with mobile SDKs should be as follows:

![mobileFlow](https://user-images.githubusercontent.com/17044577/65620185-4a4cc600-dfb9-11e9-980a-26b11603f4c5.png)

**Comment by ViktorAmelin** [comment]
Hello. I've talked with our backend developer, and he told that the chain above is correct and we don't mix endpoints.
This is what we are getting from you. Can you check what's going on there?


[checkout.rtf.zip](https://github.com/checkout/frames-ios/files/3658126/checkout.rtf.zip)

**Comment by nicolas-maalouf-cko** [comment]
Hi @ViktorAmelin 
This would happen if you call https://sandbox.checkout.com/api2/v2/payments which is an invalid URL

https://sandbox.checkout.com/api2/v2/tokens is the URL that needs to be called from the app and
https://api.sandbox.checkout.com/payments the one from your backend server

**Comment by ViktorAmelin** [comment]
@nicolas-maalouf-cko Hello. Are the links in your framework are correct:
var urlApi: String {
        switch self {
        case .live:
            return "https://api2.checkout.com/v2/"
        case .sandbox:
            return "https://sandbox.checkout.com/api2/v2/"
        }
    }

    var urlPaymentApi: String {
        switch self {
        case .live:
            return "https://api.checkout.com/"
        case .sandbox:
            return "https://sandbox.checkout.com/api2/"
        }
    }

**Comment by nicolas-maalouf-cko** [comment]
These work, but we are release an updated SDK soon with the latest URLs

**Comment by nicolas-maalouf-cko** [comment]
Hi @ViktorAmelin [3.0.1](https://github.com/checkout/frames-ios/releases/tag/3.0.1) is now released

**Comment by nunepradeepkumar** [comment]
Hi ,
   How to change the pay  button position in default frame.
