### ISSUE TITLE
Error in the Interface Builder

### ISSUE THREAD

**Issue by sprzenus** [checkout/frames-ios#34]
**Describe the bug**
Xcode shows errors in file `DetailsInputView.swift` after opening a storyboard file.
Errors:
 - line 48: 'UIButtonType' has been renamed to 'UIButton.ButtonType'
 - line 49: Cannot force unwrap value of non-optional type 'UILabel'

**To Reproduce**
Open a storyboard while the framework is imported.

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Xcode 12.3
 - Version: 3.1.1

**Comment by daven-gomes-cko** [comment]
Thanks for reporting this issue @sprzenus. This should now be fixed in 3.2.0 for `DetailsInputView`.
