### ISSUE TITLE
merchant certificate not found

### ISSUE THREAD

**Issue by Dev-iOS-Appbirds** [checkout/frames-ios#366]
**we are facing merchant_certificate_not_found error in apple pay.**

(lldb) po error
▿ TokenRequest
  ▿ serverError : ServerError
    - requestID : "4a04180b-***-44cc-***-****e426bd9"
    - errorType : "request_invalid"
    ▿ errorCodes : 1 element
      - 0 : "merchant_certificate_not_found"
    - code : 3000

(lldb) po error.localizedDescription
"The operation couldn’t be completed. (Checkout.TokenisationError.TokenRequest error 2.)"

**Comment by alex-ioja-yang-cko** [comment]
Hi @Dev-iOS-Appbirds ,

That error would be sent from our backend and is usually a sign of an incorrect setup. Could you please run through [Apple Pay Setup](https://www.checkout.com/docs/payments/payment-methods/apple-pay/set-up-apple-pay#Before_you_start) and let us know if it fixes the issue for you?

Thank you

**Comment by Dev-iOS-Appbirds** [comment]
facing **signing_request_not_found** error in https://api.checkout.com/applepay/certificates
{
    "request_id": "c4ba2fc5-****-4c2b-****-a4f405***db4",
    "error_type": "request_invalid",
    "error_codes": [
        "signing_request_not_found"
    ]
}

**Comment by Dev-iOS-Appbirds** [comment]
Thank you @alex-ioja-yang-cko
