### ISSUE TITLE
Back Button and Accepted Cards not showing on TestFlight Build

### ISSUE THREAD

**Issue by Dev-iOS-Appbirds** [checkout/frames-ios#371]
We are facing issue when we install application from TestFlight on card page we are not able to see Back button and accepted cards section whereas if we install same build via Diawi link we are able to see the back button & accepted cards section. Kindly help us understand what could be the issue
![image (4)](https://user-images.githubusercontent.com/31612250/210071557-eac6a5a8-b297-4843-a00c-07b30b0cbeaf.png)

**Comment by alex-ioja-yang-cko** [comment]
Hi @Dev-iOS-Appbirds ,

We have been made aware of this issue previously if consumed via Cocoapods.

As a result we have created [release 4.0.3](https://github.com/checkout/frames-ios/releases/tag/4.0.3) which should fix this problem.

Can you please confirm whether this helps, otherwise which version are you using and which dependency manager?

Thank you

**Comment by patrick-hoban-cko** [comment]
Hi @Dev-iOS-Appbirds closing this existing thread, but please do raise another issue if you are still facing issues after trying 4.0.3.

**Comment by qnaveed** [comment]
I am facing the same issue and using frames version 4.3.4 @melting-snowman please suggest us

**Comment by melting-snowman** [comment]
I have not been involved in the project for over 12 months @qnaveed , but I trust @okhan-okbay-cko or @patrick-hoban-cko would be able to investigate what changes may have lead to this issue reoccurring.

**Comment by okhan-okbay-cko** [comment]
Hey @qnaveed , do you have the exact same issue? (i. e. No assets on TestFlight but on Diwai)

Or are you not seeing the assets when only you use CocoaPods as the dependency manager, rather than SPM?

**Comment by okhan-okbay-cko** [comment]
Closing since this can be deemed as stale. Feel free to add a comment, re-open or create a new issue.
