### ISSUE TITLE
Does headless mode have been removed in 4.0 ?

### ISSUE THREAD

**Issue by abouroubi** [checkout/frames-ios#377]
We were using the headless mode in the version 3.0, especially the CardUtil class.
In the readme of the version 4, there is no mention of headless mode anymore, has it been removed ?

**Comment by alex-ioja-yang-cko** [comment]
Hi @abouroubi sorry for the delay in getting back to you.

Version 4.0.0 improves the security of the users data by protecting their input and facilitating the full UI journey on behalf of the application. As such, a CardUtil class should not be needed as you should no longer need to handle user inputs, formatting and additional logic that was previously covered inside the CardUtil class.

**Comment by abouroubi** [comment]
Well that's a huge change for us. It will take a lot of man days to migrate from our full custom UI to the frameworks UI, and we are not even sure that we can have the exact same UI.

For how long will you support the 3.0, because we can't afford the cost of updating to v4.

**Comment by patrick-hoban-cko** [comment]
Hey @abouroubi thanks for raising this question.

We've updated our SDKs to move away from Headless and be more UI-centric, as this is a more secure way to allow our merchants to use our SDKs, and requires lower levels of compliance. Note that we'll be supporting 3.X.X versions until 1st May 23, after that we'll recommend upgrading.

Please reach out to your CSM, who can loop me in, to discuss this further.

**Comment by patrick-hoban-cko** [comment]
Hey @abouroubi I'll close this ticket now, but if you have any further questions, please do raise another ticket and we can take a look.
Thanks,
Patrick
