### ISSUE TITLE
Text color in Text fields isn't updated after changing Light/Dark mode

### ISSUE THREAD

**Issue by UserArtem** [checkout/frames-ios#379]
`primaryFontColor` works well If you open screen initially either in dark/light mode. But if you change mode in already opened screen all text fields don't update theirs text color.

**Comment by UserArtem** [comment]
Hi @ehab-al-cko Thanks for quick response the SDK version is 4.0.4 the latest I believe

**Comment by okhan-okbay-cko** [comment]
Hi @UserArtem,

Closing this issue now since it's not planned to be supported to respond to phone setting changes in real time in the near future. We'll be tracking this with our internal tools and hopefully support it at some point 🙂
