### ISSUE TITLE
3ds redirection not working

### ISSUE THREAD

**Issue by jessjpj** [checkout/frames-ios#380]
**Describe the bug**
I am not getting the callbacks in ThreedsWebViewControllerDelegate. All I can see is a white screen and security errors.

**To Reproduce**
1. create a redirect URL
2. open the sample ios application
3. paste the redirect URL in the 3ds field.
4. tap on the button to navigate to OTP screen.
5. enter OTP "Checkout1!"
6. tap on submit button

**Expected behavior**
should be redirected to the success screen with a callback on ThreedsWebViewControllerDelegate

**Screenshots**
![Screenshot 2023-02-21 at 9 40 27 AM](https://user-images.githubusercontent.com/8969855/220257837-319679c1-d44c-4a28-b4ab-61064d4cda25.png)

**Desktop (please complete the following information):**
 - OS: Ventura
 - Xcode: 14.1

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16

**Additional context**
used sample success url: https://httpstat.us/200, https://example.com/success, tried a postman url: https://60f26c46-7b7e-499f-8768-490a31398ba3.mock.pstmn.io/success. Nothing seems to be working. 

console log:
[frames.txt](https://github.com/checkout/frames-ios/files/10790011/frames.txt)

**Comment by emmessess** [comment]
> **Describe the bug** I am not getting the callbacks in ThreedsWebViewControllerDelegate. All I can see is a white screen and security errors.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. create a redirect URL
> 2. open the sample ios application
> 3. paste the redirect URL in the 3ds field.
> 4. tap on the button to navigate to OTP screen.
> 5. enter OTP "Checkout1!"
> 6. tap on submit button
> 
> **Expected behavior** should be redirected to the success screen with a callback on ThreedsWebViewControllerDelegate
> 
> **Screenshots** ![Screenshot 2023-02-21 at 9 40 27 AM](https://user-images.githubusercontent.com/8969855/220257837-319679c1-d44c-4a28-b4ab-61064d4cda25.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ventura
> * Xcode: 14.1
> 
> **Smartphone (please complete the following information):**
> 
> * Device: iPhone 11
> * OS: iOS 16
> 
> **Additional context** used sample success url: https://httpstat.us/200, https://example.com/success, tried a postman url: https://60f26c46-7b7e-499f-8768-490a31398ba3.mock.pstmn.io/success. Nothing seems to be working.
> 
> console log: [frames.txt](https://github.com/checkout/frames-ios/files/10790011/frames.txt)

Same issue with me, using sample code provided in iOS documentation. Using my own success and Failure URL but the delegate is not fired.

**Comment by jessjpj** [comment]
> > **Describe the bug** I am not getting the callbacks in ThreedsWebViewControllerDelegate. All I can see is a white screen and security errors.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. create a redirect URL
> > 2. open the sample ios application
> > 3. paste the redirect URL in the 3ds field.
> > 4. tap on the button to navigate to OTP screen.
> > 5. enter OTP "Checkout1!"
> > 6. tap on submit button
> > 
> > **Expected behavior** should be redirected to the success screen with a callback on ThreedsWebViewControllerDelegate
> > **Screenshots** ![Screenshot 2023-02-21 at 9 40 27 AM](https://user-images.githubusercontent.com/8969855/220257837-319679c1-d44c-4a28-b4ab-61064d4cda25.png)
> > **Desktop (please complete the following information):**
> > 
> > * OS: Ventura
> > * Xcode: 14.1
> > 
> > **Smartphone (please complete the following information):**
> > 
> > * Device: iPhone 11
> > * OS: iOS 16
> > 
> > **Additional context** used sample success url: https://httpstat.us/200, https://example.com/success, tried a postman url: https://60f26c46-7b7e-499f-8768-490a31398ba3.mock.pstmn.io/success. Nothing seems to be working.
> > console log: [frames.txt](https://github.com/checkout/frames-ios/files/10790011/frames.txt)
> 
> Same issue with me, using sample code provided in iOS documentation. Using my own success and Failure URL but the delegate is not fired.

I found the solution. We have to set the success URL and failure URL while generating the redirect URL. and we have to pass the same success and failure ULRs to 3dscontroller. This will get the proper callback.
