### ISSUE TITLE
Crash when use payment view

### ISSUE THREAD

**Issue by mrahmed017** [checkout/frames-ios#450]
Crash when push the view from payment builder 
This is the log for error

![image](https://github.com/checkout/frames-ios/assets/71335484/3d38c21a-01a6-4d6a-befe-0a42abfd2f47)

**Comment by mrahmed017** [comment]
This the code


![image](https://github.com/checkout/frames-ios/assets/71335484/e35f42ea-497c-4590-8462-0891a057b638)

![image](https://github.com/checkout/frames-ios/assets/71335484/3df1a35a-7fe0-4114-a1c9-6cc3f67aaa3b)

**Comment by mrahmed017** [comment]
<img width="1078" alt="Screenshot 2023-08-22 at 10 32 45 AM" src="https://github.com/checkout/frames-ios/assets/71335484/f9a8685f-49ca-4295-827d-76b3922d40aa">

**Comment by mrahmed017** [comment]
<img width="1078" alt="Screenshot 2023-08-22 at 10 32 45 AM" src="https://github.com/checkout/frames-ios/assets/71335484/7f0ef529-668e-47c7-bbec-51f116c4648b">

**Comment by mrahmed017** [comment]
![Screenshot 2023-08-22 at 11 04 34 AM](https://github.com/checkout/frames-ios/assets/71335484/7cc05537-a18a-4848-8289-edd81d64aa84)

**Comment by okhan-okbay-cko** [comment]
hey @mrahmed017, we're checking this and will be back to you soon

**Comment by okhan-okbay-cko** [comment]
sent a sample project through Slack. Have you received that? @mrahmed017

**Comment by mrahmed017** [comment]
No I don't 
I have downloaded the simple project from Github, I followed the steps but crash still show when push or present the payment view

**Comment by okhan-okbay-cko** [comment]
Can you please have a look at this project that's created by the sample code that you provided above? It does not show any errors so, if you can reproduce the error on it and send it back, we can have a detailed look. @mrahmed017 

[Error-237495.zip](https://github.com/checkout/frames-ios/files/12411261/Error-237495.zip)

**Comment by mrahmed017** [comment]
@okhan-okbay-cko project you sent is working, and the same code when used in my project crash 
[Checkout.zip](https://github.com/checkout/frames-ios/files/12411398/Checkout.zip)
this archive contains video, images and crash log
and if you want to meet on(TeamViewer Or Meet) just let me know

**Comment by okhan-okbay-cko** [comment]
I had already investigated the screenshots and the logs you provided. 

The project that I sent here is the only code and integration that we currently provide and it works when done as suggested. There is no property called as `tableView` inside the `PaymentViewController`, so, I'll assume this is an error that comes from your implementation. @mrahmed017

**Comment by mrahmed017** [comment]
@okhan-okbay-cko What do you suggest that we do now to work properly, I removed the old version (3,0) permanently and downloaded the new version (4.2) twice

**Comment by okhan-okbay-cko** [comment]
If you can send a project that reproduces this issue, then I can have a look at the problem. @mrahmed017

**Comment by mrahmed017** [comment]
Oky no problem, but I prefer send it by email ( or any private channel)

**Comment by okhan-okbay-cko** [comment]
sure, you can send it through Slack as well. @mrahmed017

**Comment by mrahmed017** [comment]
We already with checkout with Slack 
![image](https://github.com/checkout/frames-ios/assets/71335484/f46bc46d-d564-47eb-87bb-03061c3984f0)

**Comment by okhan-okbay-cko** [comment]
Hey, thanks for your reply, let's take this offline and loop in with your customer success manager and/or implementation engineer to discuss further. @mrahmed017
