### ISSUE TITLE
PhoneNumberTextField definition conflict

### ISSUE THREAD

**Issue by barniques** [checkout/frames-ios#46]
Recently we have found a bug, which is blocking our integration of your iOS sdk

In our project we use third-party dependencies with Objc code. Because of this, Cocoapods generates Objc headers for swift files automatically. 
After installing yours sdk, our project does not compile with this error:
` 'PhoneNumberTextField' has different definitions in different modules; first difference is definition in module 'PhoneNumberKit.Swift' found return type is 'void' `

The investigation shows that PhoneNumberTextField is declared in your sdk and PhoneNumberKit, which installed through cocoapods. Similar problems in other pods:
https://github.com/onevcat/Kingfisher/issues/1530
https://github.com/Adyen/adyen-ios/issues/257
https://github.com/xmartlabs/Eureka/issues/2109
and apple developer forum
https://developer.apple.com/forums/thread/658012?page=3

Possible solutions:
- Do not generate headers for ObjC. SWIFT_INSTALL_OBJC_HEADER = NO
- Set an explicit prefix for ObjC which will resolve namespacing
- Add PhoneNumberKit as Cocoapods dependency in Frames.podspec

Because we still use objc third-party dependencies, we can’t solve this problem through SWIFT_INSTALL_OBJC_HEADER, neither the third option may take a while to fix

So we suggest to fix this problem through explicit prefix for ObjC like this
```
@objc(CKO)
open class PhoneNumberTextField: UITextField, UITextFieldDelegate {
```

We can’t reproduce this problem in sample project, because our project is not simple enough. 
But we can be in touch and test this issue through custom branch via cocoapods

**Comment by harry-brown-cko** [comment]
Hi @barniques,

We are currently working on a solution to this, which will be fixed in our next release. We expect to follow your third suggestion (adding `PhoneNumberKit` as a dependency).
