### ISSUE TITLE
CkoPhoneNumber coding key query

### ISSUE THREAD

**Issue by adamwaite** [checkout/frames-ios#47]
Hi.

Just wanted to query something I've noticed in the API contracts for registering a card in the payment flows (`POST https://api.checkout.com/tokens`).

The `CkoAddress` type (and other associated types, like `CkoCardTokenRequest`) is encoded using snake case keys (https://github.com/checkout/frames-ios/blob/master/Source/CkoAddress.swift), as can be seen in the `Encodable` implementation. `addressLine1` becomes `address_line1` for example.

However `CkoPhoneNumber` is not encoded with any custom `CodingKeys` (https://github.com/checkout/frames-ios/blob/master/Source/CkoPhoneNumber.swift) and will therefore take the standard swift case convention e.g. `countryCode` remains as `countryCode`.

Is this a known quirk on the API? Or maybe a bug in this SDK?

**Comment by deepesh-vasthimal-cko** [comment]
@adamwaite Thanks for raising this with us. We are aware of this now and we will plan to make a fix in the SDK with our next release. Thanks

**Comment by deepesh-vasthimal-cko** [comment]
@adamwaite , This is now fixed as part of our latest release 3.4.0. Please feel free to re-open this if you have any further questions.

**Comment by adamwaite** [comment]
Hey CkoAddress still implements `CodingKeys`, is that an edge case?

**Comment by adamwaite** [comment]
Also `CkoCardTokenRequest`

**Comment by daven-gomes-cko** [comment]
Hey @adamwaite, the update was a quick fix that just addressed the Codable objects that were causing errors. We'll work on improving the whole decoding/encoding logic for a future update. 🙂
