### ISSUE TITLE
Problem with customisation.

### ISSUE THREAD

**Issue by maulikshah09** [checkout/frames-ios#501]
Hello sir/mam,

 I create my own text filed but the problem is I can't access icon and method. I share screenshot so you got better.

I want UI like this. You have 4 screen that I check in frames Demo but it is not possible to create  like this.i create UI like this and I used payment methods for payment. everything working fine. but now issue is that I can't format textfield and I can't access payment type icon.

![Simulator Screenshot - iPhone 15 Pro - 2023-12-18 at 01 10 59](https://github.com/checkout/frames-ios/assets/11289579/7ae5700d-77fc-4b71-a710-0182dae1ef6a)

according to my research 

I try this code in my Viewcontroller but it can't access. it is not public protocol. From below method I got text and icon that I debug in sdk code. 
<img width="1092" alt="Screenshot 2023-12-18 at 1 13 56 AM" src="https://github.com/checkout/frames-ios/assets/11289579/3ab3fecd-752b-4b22-908d-690ccf63113e">

<img width="866" alt="Screenshot 2023-12-18 at 1 16 40 AM" src="https://github.com/checkout/frames-ios/assets/11289579/a876b0f4-d78a-401a-be1f-c0c93428b9d7">

I want this method public how can I do? can you do that for me..this is our client requirement so we create UI like this.

Please help me .
Thank you.

**Comment by maulikshah09** [comment]
Hello @ehab-al-cko 

I created common text filed with material design.  now we want above UI.. Payment view controller can't achieve that I checked the code also.. Please help me to public that methods or provide me alternative.. we are in market now from last 2 year so we can't change anything we need public that methods.

**Comment by patrick-hoban-cko** [comment]
Hi @maulikshah09, can you be more specific about your requirements here? Are you trying to load the payment form into an action sheet? What exactly is it that you can't do with the current prebuilt UI that we offer?

**Comment by maulikshah09** [comment]
@patrick-hoban-cko If you can do above method public then everything is done. that method is providing icon and type of card.

**Comment by patrick-hoban-cko** [comment]
@maulikshah09 could you explain why you would need those methods public, i.e. what are you trying to achieve with the icons/text? 

As Ehab mentioned above, we don't allow access to the content of text fields for security reasons. This would include the positioning of the text, where the scheme icon shows in the card number field, and in the field validation itself that verifies the card number/expiry date/CVV.

**Comment by maulikshah09** [comment]
@patrick-hoban-cko I checked your framework there is no security for that. We want to show the icon on left side and format the textfield.

According to your protocol it is provided text that is formatted and icon of the card.

**Comment by patrick-hoban-cko** [comment]
Hi @maulikshah09, the prebuilt UI will automatically place the icon on the left hand side and format the text in the fields like that. I would recommend taking a look at the sample app provided to see an example integration for the prebuilt UI we have that should fulfil your requirements!

**Comment by maulikshah09** [comment]
@patrick-hoban-cko it is not fulfilling our requirement check our UI I attached the screenshot. I think I have to find the way from myself. no one helping me here...

It need to convert that method to public and all problem solve. I checked sdk code.. there is no security related that text filed and that methods. If you can help me then please do it.

your sdk is not customizable. My application have Material design and client want this design. My application is live from 2 years we are not using prebuilt UI.. above UI is my own UI.

**Comment by patrick-hoban-cko** [comment]
Hi @maulikshah09, thanks for all your points above.

To avoid a lot of back and forth on here, let's take this one offline and involve your dedicated Solutions Engineer, so that I can understand your requirements a bit further and explain the capabilities of the Frames SDKs. 

Best,

Patrick

**Comment by maulikshah09** [comment]
HI @patrick-hoban-cko you don't have to do anything... just this protocol you have to do public.if it is public then I can achieve the formatted text and icon. If you set dedicated solution engineer then please assign this task. we can take google Meet if you can available. we are not changing any UI because of our application is live from last 2 year.  

[https://private-user-images.githubusercontent.com/11289579/291100645-a876b0f4-d78a-401a-be1f-c0c93428b9d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzQ5MTQsIm5iZiI6MTcwNDczNDYxNCwicGF0aCI6Ii8xMTI4OTU3OS8yOTExMDA2NDUtYTg3NmIwZjQtZDc4YS00MDFhLWJlMWYtYzBjOTM0MjhiOWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE3MjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNjFmMGY3ZTk5NmNmM2QwNjliNmYxOTFhMzY0NmFlMDcxMDdlMGVlMDk2NDM1YWUyNTQ3YjQ2ZTBhNzE0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vD2I9P9-_3w2YkfGhcOdJNnvYcjfzjA-I4rNqlZtAIE](url)

**Comment by okhan-okbay-cko** [comment]
Hey all, considering that this has been taken to be discussed via other channels, I'm closing this issue now. Feel free to re-open or to create a new one 🙏

**Comment by maulikshah09** [comment]
@patrick-hoban-cko  @okhan-okbay-cko Closing Ticket is not solution.. I can't find any solution here.

**Comment by patrick-hoban-cko** [comment]
Hi @maulikshah09, I was told by your solutions engineer that they had discussed with you. Let me ping them and they can reach out again.

**Comment by maulikshah09** [comment]
@patrick-hoban-cko  We need this thing asap. We have 3 applications that we intigrated checkout. all application is for same client.. client want that thing in all application we stuck now. we choose your SDK because your SDK Is customisable.. above UI we developed in all application. IF we choose your UI then all application we have to rework for payment.. we don't have time to rework. I hope you provide solution or I need to customise your pod code. 

Please tell me if I have to do.

**Comment by maulikshah09** [comment]
@patrick-hoban-cko OK I am waiting for your response.

**Comment by maulikshah09** [comment]
@patrick-hoban-cko Can you tell me how much time I have to wait.. if I have to work my self then tell me I can customise the code.

**Comment by maulikshah09** [comment]
@okhan-okbay-cko no problem I just got the type that I need.. according to type I show the images..
