### ISSUE TITLE
Form scrolling to the top and navigation bar not hiding

### ISSUE THREAD

**Issue by itsAyan01** [checkout/frames-ios#536]
Scrollview scrolls to top as soon as select any input field and also the navigation bar is not hiding.

i have integrated the sdk in swiftUI using UIViewControllerRepresentableView now everything is working fine except that scrolling issue

**Screenshots**

https://github.com/checkout/frames-ios/assets/136585796/f3d827ec-35b8-4672-b443-3ceeb76d8e75

**Smartphone (please complete the following information):**
 - Device: [iPhone 13]
 - OS: [iOS 17]

**Comment by okhan-okbay-cko** [comment]
Hey, can we see the code? How are you wrapping it?

**Comment by itsAyan01** [comment]
yeh sure,
here is the code

struct FramesCardSdkRepresentableView: UIViewControllerRepresentable {

    @ObservedObject var cardSdkVM: CheckoutCardSdkViewModel
    @ObservedObject var checkoutVM: CheckoutViewModel
    @Binding var showCardSdkView: Bool
    var payableAmount: String
    
    func makeUIViewController(context: Context) -> some UIViewController {
        let vc = PaymentFormFactory.buildViewController(configuration: getSdkConfiguration(),
                                                        style: PaymentStyle(
                                                            paymentFormStyle: getPaymentFormThemeStyle()
                                                        ))
        { result in
            onPaymentResponse(result: result)
        }
        return vc
    }
    
    func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) { }
    
    func getPaymentFormThemeStyle() -> PaymentFormStyle {
        // Declare the theme object with the minimum required properties
        var theme = Theme(
            primaryFontColor: UIColor(Color.blackTextColor),
            secondaryFontColor: UIColor(Color.placeholderColor),
            buttonFontColor: .black,
            errorFontColor: .red,
            backgroundColor: UIColor(Color.backgroundColor),
            errorBorderColor: .red)
        
        // Add border and corner radius around text inputs
        theme.textInputBackgroundColor = UIColor(Color.listBackgroundColor)
        theme.textInputBorderRadius = 12
        
        var paymentFormStyle = theme.buildPaymentForm(headerView: theme.buildPaymentHeader(title: LocalizableStrings.paymentDetails.localizedString,
                                                                                           subtitle: LocalizableStrings.acceptingPaymentMethods.localizedString),
                                                      addBillingButton: nil,
                                                      billingSummary: nil,
                                                      cardholder: theme.buildPaymentInput(textFieldPlaceholder: LocalizableStrings.cardholder.localizedString,
                                                                                          isTextFieldNumericInput: false,
                                                                                          titleText: LocalizableStrings.cardholderName.localizedString,
                                                                                          errorText: LocalizableStrings.invalidName.localizedString),
                                                      cardNumber: theme.buildPaymentInput(isTextFieldNumericInput: true,
                                                                                          titleText: LocalizableStrings.cardNumber.localizedString,
                                                                                          errorText: LocalizableStrings.invalidCardNumber.localizedString),
                                                      expiryDate: theme.buildPaymentInput(textFieldPlaceholder: LocalizableStrings.expDatePlaceholder.localizedString,
                                                                                          isTextFieldNumericInput: false,
                                                                                          titleText: LocalizableStrings.expDate.localizedString,
                                                                                          errorText: LocalizableStrings.enterValideExpDate.localizedString),
                                                      securityCode: theme.buildPaymentInput(isTextFieldNumericInput: true,
                                                                                            titleText: LocalizableStrings.cvv.localizedString,
                                                                                            errorText: LocalizableStrings.enterValidCvv.localizedString),
                                                      payButton: theme.buildPayButton(text: LocalizableStrings.pay.localizedString + " " + payableAmount))
        
        let buttonBorderStyle = ButtonBorderStyle(cornerRadius: SizeConstants.buttonCornerRadius,
                                                  borderWidth: 1,
                                                  normalColor: .clear,
                                                  focusColor: .clear,
                                                  errorColor: .clear,
                                                  edges: .all,
                                                  corners: .allCorners)
        
        let themePayButton = NewButtonStyle(isEnabled: paymentFormStyle.payButton.isEnabled,
                                            disabledTextColor: .white,
                                            disabledTintColor: .gray,
                                            activeTintColor: UIColor(Color.primaryColor),
                                            imageTintColor: .black,
                                            textLeading: 0,
                                            height: SizeConstants.buttonHeight,
                                            width: 300,
                                            textAlignment: .center,
                                            isHidden: false,
                                            text: LocalizableStrings.pay.localizedString + " " + payableAmount,
                                            font: .boldSystemFont(ofSize: 16),
                                            backgroundColor: UIColor(Color.primaryColor),
                                            textColor: UIColor(Color.black), borderStyle: buttonBorderStyle)
        paymentFormStyle.payButton = themePayButton
        return paymentFormStyle
    }
    
    func onPaymentResponse(result: Result<TokenDetails, TokenisationError.TokenRequest>) {
        DispatchQueue.main.async {
            UIApplication.dismissKeyboard()
        }
        switch result {
        case .failure(let failure):
            if failure == .userCancelled {
                /* Depending on needs, User Cancelled can be handled as an individual
                 failure to complete, an error, or simply a callback that control is returned */
                print("User has cancelled")
                cardSdkVM.alertMessage = "User has cancelled"
            } else {
                print("Failed, received error", failure.localizedDescription)
                cardSdkVM.alertMessage = "User has cancelled \(failure.localizedDescription)"
            }
            cardSdkVM.showTopAlert = true
        case .success(let tokenDetails):
            print("Success, received token", tokenDetails.token)
            DispatchQueue.main.async {
                cardSdkVM.cardToken = tokenDetails.token
                cardSdkVM.showSaveCardDialog = true
            }
        }
    }
    
    func getSdkConfiguration() -> PaymentFormConfiguration {
        let configuration = PaymentFormConfiguration(apiKey: "",
                                                     environment: .sandbox,
                                                     supportedSchemes: [.visa, .mada, .mastercard],
                                                     billingFormData: getBillingData())
        return configuration
    }
    
    func getBillingData() -> BillingForm {
        let country = Country(iso3166Alpha2: "SA")
        let address = Address(
            addressLine1: "",
            addressLine2: "",
            city: "",
            state: "",
            zip: "",
            country: country)
        let phone = Phone(number: "\(UDManager.shared.getString(forKey: .phoneCode)) \(UDManager.shared.getString(forKey: .phoneNumber))",
                          country: country)
        print(phone)
        return BillingForm(name: "\(UDManager.shared.getString(forKey: .firstName)) \(UDManager.shared.getString(forKey: .lastName))",
                           address: address,
                           phone: phone)
    }
}

**Comment by itsAyan01** [comment]
hey @okhan-okbay-cko is there any update on this ?

**Comment by okhan-okbay-cko** [comment]
Hey, unfortunately not yet. We'll put this in the priority queue and will act accordingly. Thanks for understanding.

**Comment by okhan-okbay-cko** [comment]
Hey,

How are you presenting `FramesCardSdkRepresentableView`? Is it inside a NavigationView? If so, can you try not adding an additional navigation bar when you present that?

**Comment by itsAyan01** [comment]
yes it is inside navigation view. I have also tried removing that custom navigation bar but it didn't worked, getting the same result. right now i am presenting it on a fullScreenCover but the result is still not good.

https://github.com/checkout/frames-ios/assets/136585796/b61d1105-7b99-4803-8788-3f6cc124d012

**Comment by itsAyan01** [comment]
without custom navigation bar ->

https://github.com/checkout/frames-ios/assets/136585796/e36e6e8e-4fd8-4776-8b77-761119e07f3a

**Comment by okhan-okbay-cko** [comment]
Hey, looks like you found a workaround for the additional space on top! 

To avoid double-auto-scrolling issue (1 from SwiftUI and 1 from Frames SDK), we would need to release a new version, which we don't have a plan for right now. 

You can have a hack-y workaround to that by doing something like below in your wrapper: 

```swift
func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) {
    print("update called")

    DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
      NotificationCenter.default.removeObserver(uiViewController, name: UIResponder.keyboardWillShowNotification, object: nil)

      NotificationCenter.default.removeObserver(uiViewController, name: UIResponder.keyboardWillHideNotification, object: nil)
    }
  }
