### ISSUE TITLE
Errors when using 3.4.1

### ISSUE THREAD

**Issue by sebskuse** [checkout/frames-ios#66]
**Describe the bug**

Hi,

We use `frames-ios` using `Carthage`, and last night I merged the upgrade to 3.4.1 for our CI system to pick up. This had required us to change references to `Frames` from `FramesIos` in source, and I had linked the new dependencies registered in the `Cartfile` in the host application (as we do with other Carthage dependencies).

Everything worked as expected till our nightly AppStore Validate job ran, and we received the following from Apple:

```
[00:53:06]: CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.roymarmelstein.PhoneNumberKit' under the iOS application 'OurApp.app'. (1091)
[00:53:06]: CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.alamofire.Alamofire' under the iOS application 'OurApp.app'. (1091)
[00:53:06]: Invalid Bundle. The bundle at 'OurApp.app/Frameworks/Frames.framework' contains disallowed nested bundles. (1091)
[00:53:06]: Invalid Bundle. The bundle at 'OurApp.app/Frameworks/Frames.framework' contains disallowed file 'Frameworks'. (1091)

```

So I'm guessing both of these dependencies are actually embedded in Frames, rather than simply being linked. I attempted to unlink these from the main binary, but now we're seeing issues running tests:

```
Could not find module 'Alamofire' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7
```

Repeat for every source file in that target.

My first thought would be to only _link_ `Alamofire` and `NumberKit` in `Frames` rather than embedding them - leaving the host application to supply the frameworks, as this is standard practice.

**To Reproduce**
1. Link `Frames`
2. Follow steps described above
3. Receive either an error from Apple or an error trying to test.

**Expected behavior**
The framework should work as expected

**Comment by harry-brown-cko** [comment]
Hey @sebskuse , sorry to hear that you're having issues with Frames again. We've unembedded the frameworks from Frames in the `develop` branch. Can you please check if this has fixed your issue? If so we can do a release that includes this fix.

NB. Code in `develop` is not verified for production and should not be pushed to customers.

**Comment by sebskuse** [comment]
Hi @harry-brown-cko, I'll pull develop in as a dependency and smoke test that against CI and the AppStore - will let you know how we get on

**Comment by sebskuse** [comment]
Hey @harry-brown-cko, given that a go (resolves to commit 698046fd8ba17ad614d95ca103a59d473d0d42d1).

I'm getting a compilation error with this now:
`could not find module 'Frames' for target 'arm64-apple-ios'; found: armv7-apple-ios, arm, armv7`

It looks like the xcframework architectures being built don't match what we were seeing with the older version (and other Carthage dependencies - it looks like `arm64` is being omitted somewhere?):

![Screenshot 2021-04-21 at 19 49 59](https://user-images.githubusercontent.com/465802/115605708-c2d15100-a2da-11eb-9ab8-0478fd052bb2.png)

I also notice that we are now required to link `CheckoutEventLoggerKit` in our app. As you're probably aware, each dynamic framework an app links slows down app startup time - we're now at 4 dynamic frameworks for Frames (Frames, Alamofire, PhoneNumberKit, CheckoutEventLoggerKit). This appears to be an internal dependency, so doesn't feel right exposing this to the consumer application - maybe a static library makes more sense if you're looking for code separation? That way you can separate the code into a separate framework, but it gets compiled down into a single binary Frames for the consumer.

**Comment by harry-brown-cko** [comment]
Hey @sebskuse I think the issues you mentioned are now fixed. Would you mind checking the develop branch again? Thanks in advance!

**Comment by sebskuse** [comment]
Hi @harry-brown-cko, thanks for the update - I've updated our branch to the latest commit on develop (df9c3f1d6cb0a60117ee11a3b1b801c065ade1e6) and it looks like everything has compiled correctly and tests have passed, so looks good!

**Comment by harry-brown-cko** [comment]
Thanks @sebskuse for being patient with us whilst sorting out this issue. Closing it now and we expect the fixes to go out in the next release

**Comment by sebskuse** [comment]
No problem, thanks for sorting.
