### ISSUE TITLE
Billing addressLines missing in CkoCardTokenResponse

### ISSUE THREAD

**Issue by sebskuse** [checkout/frames-ios#72]
**Describe the bug**
I've just gotten round to upgrading us from 3.3.0 to 3.4.2, and just caught a potential problem in that the token response no longer seems to contain the billing addressLines. 

We're definitely setting these on the checkout controller in the same way as on 3.3.0 (the only source changes are FramesIos -> Frames in the codebase), and switching back to 3.3.0 works as expected.

**To Reproduce**
1. Set a billing address with addressViewController.setFields(address:phone) (verify addressLine1 / 2 are set)
2. Go through checkout journey
3. Receive callback to `func onTapDone(controller: CardViewController, cardToken: CkoCardTokenResponse?, status: CheckoutTokenStatus)`
4. Inspect `cardToken` and see addressLines are `nil`.

**Expected behavior**
Address lines should be present

**Comment by deepesh-vasthimal-cko** [comment]
@sebskuse. Thank you for raising this issue. I am able to reproduce this and will soon plan for a fix.

**Comment by deepesh-vasthimal-cko** [comment]
@sebskuse This is now fixed in latest release. Please refer : https://github.com/checkout/frames-ios/releases/tag/3.4.3
