### ISSUE TITLE
Issues with iOS Example Custom

### ISSUE THREAD

**Issue by abouroubi** [checkout/frames-ios#74]
**Describe the bug**
I cloned the repository for iOS Example Custom and run `pod install`.
After opening the workspace with XCode, I changed the public key and started the project on the iPhone SE Emulator, I enter the test card '4242 4242 4242 4242' with '10/26' as exp date and '100' as CVV, and I tap the button, this error apear:
`Frames.NetworkError.objectDeallocatedUnexpectedly`.

**Expected behavior**
I receive a card token.

**Smartphone (please complete the following information):**
 - Device: iPhone SE Emulator
 - OS: iOS 14

**Comment by deepesh-vasthimal-cko** [comment]
@abouroubi Thanks for raising this issue, we are aware of this and will soon apply a fix. Meanwhile you can use our other iOS examples like [https://github.com/checkout/frames-ios/tree/master/iOS%20Example%20Frame] if you like to see how token is generated.
