### ISSUE TITLE
3ds implementation for custom UI Flow

### ISSUE THREAD

**Issue by gravindragupta90** [checkout/frames-ios#99]
Hi,

I am trying to integrate the iOS sdk with the custom UI as shown in the iOS Example Custom. I am looking to add the 3Ds implementation but could not find any documentation to implement it for iOS.

We have successfully implemented for the android-sdk as it's clearly documented in the git repo.
/////////////// Android Snippet ////////////////
```
private final PaymentForm.On3DSFinished m3DSecureListener = new PaymentForm.On3DSFinished() {
    @Override
    public void onSuccess(String token) {
        displayMessage("Result", "Authentication success: " + token);
    }

    @Override
    public void onError(String errorMessage) {
        displayMessage("Result", "Authentication failure: " + errorMessage);
    }
};
```
/////////////// End //////////////////////
**Note** : Looking for something similar for iOS.
Kindly let me know if there is any way to add the 3Ds for the iOS.
I have found the ThreedsWebViewController but on the callback methods we are not able to receive any sid_token as it is received in the android-sdk version as mentioned above in snippet.

It would be really helpful if i could get e sample to integrate.
Kindly advise me to proceed further.

**Comment by deepesh-vasthimal-cko** [comment]
Hi @gravindragupta90 The sid_token is currently not been added to the ThreedsWebViewController call back methods for iOS. This is something we are working on and will be available in our next release.

**Comment by deepesh-vasthimal-cko** [comment]
@gravindragupta90 The 3.5.0 release was made yesterday with examples on how to handle 3DS call back. Also we are only passing back the token on success case in this release. However if you feel this is really required for failure scenario please feel free to raise a new issue and we can plan to put this in our next release. Please note we highly recommend you do carry our regression testing after you upgrade to our new release and before you release your apps into production.
